# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 510)
        MainWindow.setMinimumSize(QtCore.QSize(504, 510))
        MainWindow.setMaximumSize(QtCore.QSize(504, 510))
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(60, 120, 391, 31))
        self.openFileButton.setObjectName("openFileButton")
        self.labelFile = QtWidgets.QLabel(self.centralwidget)
        self.labelFile.setGeometry(QtCore.QRect(20, 120, 31, 31))
        self.labelFile.setText("")
        self.labelFile.setPixmap(QtGui.QPixmap(":/folder_open/folder_open.png"))
        self.labelFile.setScaledContents(True)
        self.labelFile.setIndent(0)
        self.labelFile.setObjectName("labelFile")
        self.removeFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeFileButton.setGeometry(QtCore.QRect(460, 120, 31, 31))
        self.removeFileButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/delete_file/delete_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeFileButton.setIcon(icon)
        self.removeFileButton.setIconSize(QtCore.QSize(25, 25))
        self.removeFileButton.setObjectName("removeFileButton")
        self.textBoxMD5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBoxMD5.setGeometry(QtCore.QRect(120, 170, 331, 31))
        self.textBoxMD5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBoxMD5.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textBoxMD5.setLineWrapColumnOrWidth(0)
        self.textBoxMD5.setReadOnly(True)
        self.textBoxMD5.setPlaceholderText("")
        self.textBoxMD5.setObjectName("textBoxMD5")
        self.labelMD5 = QtWidgets.QLabel(self.centralwidget)
        self.labelMD5.setGeometry(QtCore.QRect(50, 170, 61, 31))
        self.labelMD5.setObjectName("labelMD5")
        self.textBoxSHA256 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBoxSHA256.setGeometry(QtCore.QRect(120, 210, 331, 51))
        self.textBoxSHA256.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBoxSHA256.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textBoxSHA256.setLineWrapColumnOrWidth(0)
        self.textBoxSHA256.setReadOnly(True)
        self.textBoxSHA256.setTabStopWidth(80)
        self.textBoxSHA256.setPlaceholderText("")
        self.textBoxSHA256.setObjectName("textBoxSHA256")
        self.labelSHA256 = QtWidgets.QLabel(self.centralwidget)
        self.labelSHA256.setGeometry(QtCore.QRect(50, 220, 61, 31))
        self.labelSHA256.setObjectName("labelSHA256")
        self.textBoxSHA512 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBoxSHA512.setGeometry(QtCore.QRect(120, 270, 331, 91))
        self.textBoxSHA512.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBoxSHA512.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textBoxSHA512.setLineWrapColumnOrWidth(0)
        self.textBoxSHA512.setReadOnly(True)
        self.textBoxSHA512.setTabStopWidth(80)
        self.textBoxSHA512.setPlaceholderText("")
        self.textBoxSHA512.setObjectName("textBoxSHA512")
        self.labelSHA512 = QtWidgets.QLabel(self.centralwidget)
        self.labelSHA512.setGeometry(QtCore.QRect(50, 270, 61, 31))
        self.labelSHA512.setObjectName("labelSHA512")
        self.labelDoneMD5 = QtWidgets.QLabel(self.centralwidget)
        self.labelDoneMD5.setGeometry(QtCore.QRect(460, 170, 31, 31))
        self.labelDoneMD5.setText("")
        self.labelDoneMD5.setScaledContents(True)
        self.labelDoneMD5.setIndent(-1)
        self.labelDoneMD5.setObjectName("labelDoneMD5")
        self.labelDoneSHA256 = QtWidgets.QLabel(self.centralwidget)
        self.labelDoneSHA256.setGeometry(QtCore.QRect(460, 220, 31, 31))
        self.labelDoneSHA256.setText("")
        self.labelDoneSHA256.setScaledContents(True)
        self.labelDoneSHA256.setObjectName("labelDoneSHA256")
        self.labelDoneSHA512 = QtWidgets.QLabel(self.centralwidget)
        self.labelDoneSHA512.setGeometry(QtCore.QRect(460, 270, 31, 31))
        self.labelDoneSHA512.setText("")
        self.labelDoneSHA512.setScaledContents(True)
        self.labelDoneSHA512.setObjectName("labelDoneSHA512")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 381, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/header/header.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBoxCheck = QtWidgets.QTextEdit(self.centralwidget)
        self.textBoxCheck.setGeometry(QtCore.QRect(120, 370, 331, 70))
        self.textBoxCheck.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBoxCheck.setObjectName("textBoxCheck")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(120, 450, 88, 27))
        self.clearButton.setObjectName("clearButton")
        self.clipboardButton = QtWidgets.QPushButton(self.centralwidget)
        self.clipboardButton.setGeometry(QtCore.QRect(220, 450, 131, 27))
        self.clipboardButton.setObjectName("clipboardButton")
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkButton.setGeometry(QtCore.QRect(360, 450, 91, 27))
        self.checkButton.setObjectName("checkButton")
        self.labelHashBox = QtWidgets.QLabel(self.centralwidget)
        self.labelHashBox.setGeometry(QtCore.QRect(40, 380, 71, 21))
        self.labelHashBox.setObjectName("labelHashBox")
        self.clipboardMD5Button = QtWidgets.QPushButton(self.centralwidget)
        self.clipboardMD5Button.setGeometry(QtCore.QRect(10, 170, 31, 31))
        self.clipboardMD5Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/clipboard/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clipboardMD5Button.setIcon(icon1)
        self.clipboardMD5Button.setIconSize(QtCore.QSize(27, 31))
        self.clipboardMD5Button.setCheckable(False)
        self.clipboardMD5Button.setObjectName("clipboardMD5Button")
        self.clipboardSHA256Button = QtWidgets.QPushButton(self.centralwidget)
        self.clipboardSHA256Button.setGeometry(QtCore.QRect(10, 220, 31, 31))
        self.clipboardSHA256Button.setText("")
        self.clipboardSHA256Button.setIcon(icon1)
        self.clipboardSHA256Button.setIconSize(QtCore.QSize(27, 31))
        self.clipboardSHA256Button.setCheckable(False)
        self.clipboardSHA256Button.setObjectName("clipboardSHA256Button")
        self.clipboardSHA512Button = QtWidgets.QPushButton(self.centralwidget)
        self.clipboardSHA512Button.setGeometry(QtCore.QRect(10, 270, 31, 31))
        self.clipboardSHA512Button.setText("")
        self.clipboardSHA512Button.setIcon(icon1)
        self.clipboardSHA512Button.setIconSize(QtCore.QSize(27, 31))
        self.clipboardSHA512Button.setCheckable(False)
        self.clipboardSHA512Button.setObjectName("clipboardSHA512Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.clearButton.clicked.connect(self.textBoxCheck.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openFileButton.setText(_translate("MainWindow", "Click to open a file"))
        self.labelMD5.setText(_translate("MainWindow", "MD5"))
        self.labelSHA256.setText(_translate("MainWindow", "SHA256"))
        self.labelSHA512.setText(_translate("MainWindow", "SHA512"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.clipboardButton.setText(_translate("MainWindow", "Paste clipboard"))
        self.checkButton.setText(_translate("MainWindow", "Check"))
        self.labelHashBox.setText(_translate("MainWindow", "<html><head/><body><p>HashBox</p></body></html>"))

import resources_rc
